/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MeRouteImport } from './routes/me'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiInsightsRouteImport } from './routes/api/ai/insights'
import { Route as ApiPublicSyncProductRouteImport } from './routes/api/public/sync.product'
import { Route as ApiPublicSyncMicrosoftRouteImport } from './routes/api/public/sync.microsoft'
import { Route as ApiPublicSyncGoogleRouteImport } from './routes/api/public/sync.google'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInsightsRoute = ApiAiInsightsRouteImport.update({
  id: '/api/ai/insights',
  path: '/api/ai/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncProductRoute = ApiPublicSyncProductRouteImport.update({
  id: '/api/public/sync/product',
  path: '/api/public/sync/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncMicrosoftRoute = ApiPublicSyncMicrosoftRouteImport.update({
  id: '/api/public/sync/microsoft',
  path: '/api/public/sync/microsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncGoogleRoute = ApiPublicSyncGoogleRouteImport.update({
  id: '/api/public/sync/google',
  path: '/api/public/sync/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/gaps': typeof GapsRoute
  '/me': typeof MeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/public/sync/google': typeof ApiPublicSyncGoogleRoute
  '/api/public/sync/microsoft': typeof ApiPublicSyncMicrosoftRoute
  '/api/public/sync/product': typeof ApiPublicSyncProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/gaps': typeof GapsRoute
  '/me': typeof MeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/public/sync/google': typeof ApiPublicSyncGoogleRoute
  '/api/public/sync/microsoft': typeof ApiPublicSyncMicrosoftRoute
  '/api/public/sync/product': typeof ApiPublicSyncProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/gaps': typeof GapsRoute
  '/me': typeof MeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/public/sync/google': typeof ApiPublicSyncGoogleRoute
  '/api/public/sync/microsoft': typeof ApiPublicSyncMicrosoftRoute
  '/api/public/sync/product': typeof ApiPublicSyncProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/gaps'
    | '/me'
    | '/sitemap.xml'
    | '/sources'
    | '/api/ai/insights'
    | '/api/public/sync/google'
    | '/api/public/sync/microsoft'
    | '/api/public/sync/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/gaps'
    | '/me'
    | '/sitemap.xml'
    | '/sources'
    | '/api/ai/insights'
    | '/api/public/sync/google'
    | '/api/public/sync/microsoft'
    | '/api/public/sync/product'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/gaps'
    | '/me'
    | '/sitemap.xml'
    | '/sources'
    | '/api/ai/insights'
    | '/api/public/sync/google'
    | '/api/public/sync/microsoft'
    | '/api/public/sync/product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  GapsRoute: typeof GapsRoute
  MeRoute: typeof MeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  ApiAiInsightsRoute: typeof ApiAiInsightsRoute
  ApiPublicSyncGoogleRoute: typeof ApiPublicSyncGoogleRoute
  ApiPublicSyncMicrosoftRoute: typeof ApiPublicSyncMicrosoftRoute
  ApiPublicSyncProductRoute: typeof ApiPublicSyncProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/insights': {
      id: '/api/ai/insights'
      path: '/api/ai/insights'
      fullPath: '/api/ai/insights'
      preLoaderRoute: typeof ApiAiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/product': {
      id: '/api/public/sync/product'
      path: '/api/public/sync/product'
      fullPath: '/api/public/sync/product'
      preLoaderRoute: typeof ApiPublicSyncProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/microsoft': {
      id: '/api/public/sync/microsoft'
      path: '/api/public/sync/microsoft'
      fullPath: '/api/public/sync/microsoft'
      preLoaderRoute: typeof ApiPublicSyncMicrosoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/google': {
      id: '/api/public/sync/google'
      path: '/api/public/sync/google'
      fullPath: '/api/public/sync/google'
      preLoaderRoute: typeof ApiPublicSyncGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  GapsRoute: GapsRoute,
  MeRoute: MeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  ApiAiInsightsRoute: ApiAiInsightsRoute,
  ApiPublicSyncGoogleRoute: ApiPublicSyncGoogleRoute,
  ApiPublicSyncMicrosoftRoute: ApiPublicSyncMicrosoftRoute,
  ApiPublicSyncProductRoute: ApiPublicSyncProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
